### ISSUE TITLE
Add flag to apply recommended changes

### ISSUE THREAD

**Issue by miketheman** [shopkeep/pytest-black#19]
Hi there!

I like having Black be part of my test run, however I find that most projects I've worked on benefit from enabling the developer to opt in to have the changes automatically applied, thereby only requiring a cursory review and commit.

In the readme, "Changes will not be applied automatically." is clearly noted, so I was wondering if there's been any thought as to adding that functionality to the plugin?

**Comment by paddycarey** [comment]
Hi @miketheman, I think this could be a useful addition.

Personally I find myself just calling `black .` if `pytest-black` fails on a formatting issue, so one extra command, but I can see how the flag would be useful to others.

We don't currently have a usecase for this at @ work so it's unlikely we'll find time to prioritise adding such a flag, but very happy to accept a PR that does so.

**Comment by Synss** [comment]
As a user, I do not think that this is a good idea. I would not want my test suite to change any of my code.

To format code automatically, I would rather have a commit hook that runs `black` for me.

Just my 2 cents though.

**Comment by Larandar** [comment]
As a user, I think both arguments are right:
- in my CI I want the test to fail because of formating
- but when I'm running my test nonstop (for example with pytest-watch or a simple while loop) having an extra flag to tell `apply any code formatting` would be great

At the moment my IDE is configured to apply black on saving but having one more convenience would make something already great really awesome :)
